//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newdb.Models.DataEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class crate
    {
        public int Id { get; set; }
        public string Id_1 { get; set; }
        public string Zakaz { get; set; }
        public string Build { get; set; }
        public string Detal { get; set; }
        public string Quantity { get; set; }
        public string Raz { get; set; }
        public string Time_one_detal { get; set; }
        public string Time_all_detal { get; set; }
        public string Date_rec { get; set; }
        public string Date_del { get; set; }
        public string Comment { get; set; }
    }
}
