//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newdb.Models.DataEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Builds
    {
        public int Id { get; set; }
        public string Build { get; set; }
        public string Detal { get; set; }
        public string Zakaz { get; set; }
    }
}
